version: '3'
services:
#  stack-backend-service:
#    container_name: stack-backend-service
#    build: ./stack-backend-service
#    stdin_open: true
#    tty: true
#    ports:
#      - "8082:8082"
#    environment:
#      - MONGO_HOST=mongo
#      - MONGO_PORT=27017
#      - LOG_DIR=logs
#      - SPRING_PROFILES_ACTIVE=develop
#      - CRED_DIR=C:/Users/MSRILAKS/stackCred
#      - CRED_FILE=stackCredential
#    links:
#      - mongo
  stack-task-service:
    container_name: stack-task-service
    build: ./stack-task-service
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - LOG_DIR=logs
      - SPRING_PROFILES_ACTIVE=develop
    links:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example