apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stack-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: stack-task-ui
              servicePort: 80