apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stack-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: stack-task-ui
              servicePort: 80
          - path: /
            backend:
              serviceName: stack-task-ui
              servicePort: 80
          - path: /stackitdown
            backend:
              serviceName: stack-task-ui
              servicePort: 80
          - path: /health
            backend:
              serviceName: stack-task-service
              servicePort: 8080
          - path: /stack
            backend:
              serviceName: stack-task-service
              servicePort: 8080
          - path: /user/me
            backend:
              serviceName: stack-task-service
              servicePort: 8080
          - path: /oauth2/authorize
            backend:
              serviceName: stack-task-service
              servicePort: 8080
          - path: /oauth2/redirect
            backend:
              serviceName: stack-task-ui
              servicePort: 80
          - path: /login/oauth2/code/google
            backend:
              serviceName: stack-task-service
              servicePort: 8080