apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stack-ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: stack-task-ui
              servicePort: 80