apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: stack-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: stack-task-ui
              servicePort: 80
          - path: /stackitdown/*
            backend:
              serviceName: stack-task-ui
              servicePort: 80
          - path: /health
            backend:
              serviceName: stack-task-service
              servicePort: 8080
          - path: /stack
            backend:
              serviceName: stack-task-service
              servicePort: 8080